author: 
  - name: Longhai Li
    affiliation: "University of Saskatchewan"
date: today
execute:
  dir: file
  fig-width: 6
  fig-height: 6
  fig.align: center
  freeze: false

format:
  html:
    toc: false
    format-links: false
    toc-title: "Contents"
    toc-depth: 3
    page-layout: full
    code-fold: true
    number-sections: false
    df-print: paged
    highlight-style: tango
    css: resources/mystyles.css
    include-after-body:
      - resources/pagetoc.js
  pdf:
    toc: false
    toc-depth: 1
    number-sections: false
    colorlinks: true
    mainfont: "Times New Roman"
    shift-heading-level-by: -1
    geometry:
      - top=30mm
      - left=20mm

from: markdown+tex_math_single_backslash+tex_math_dollars

params:
  show_solutions: false    ## <- scalar param, not a list

