project:
  type: book
  output-dir: .
book:
  title: "Statistical Inference"
  output-file: mathstat-LLI
  author:
  - name: "Longhai Li"
    affiliation: "University of Saskatchewan"
    url: "https://longhaisk.github.io/"
  date: last-modified
  chapters:
    - index.qmd
    - introstatinf.qmd
    - decision.qmd
    - bayesian.qmd
metadata-files:
  - resources/bookstyles.yml
